import { type TileType } from "../types.js";

export const LEVEL_1_MAP: TileType[][] = [
  ["TL", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "TR", "TL", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "TR",],
  ["WV", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "PP", "WV", "WV", "PP", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "WV",],
  ["WV", "FD", "TL", "WH", "WH", "TR", "FD", "TL", "WH", "WH", "WH", "TR", "FD", "WV", "WV", "FD", "TL", "WH", "WH", "WH", "TR", "FD", "TL", "WH", "WH", "TR", "FD", "WV",],
  ["WV", "FD", "WV", "ES", "ES", "WV", "FD", "WV", "ES", "ES", "ES", "WV", "FD", "WV", "WV", "FD", "WV", "ES", "ES", "ES", "WV", "FD", "WV", "ES", "ES", "WV", "FD", "WV",],
  ["WV", "FD", "BL", "WH", "WH", "BR", "FD", "BL", "WH", "WH", "WH", "BR", "FD", "BL", "BR", "FD", "BL", "WH", "WH", "WH", "BR", "FD", "BL", "WH", "WH", "BR", "FD", "WV",],
  ["WV", "PP", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "PP", "WV",],
  ["WV", "FD", "TL", "WH", "WH", "TR", "FD", "TL", "TR", "FD", "TL", "WH", "WH", "WH", "WH", "WH", "WH", "TR", "FD", "TL", "TR", "FD", "TL", "WH", "WH", "TR", "FD", "WV",],
  ["WV", "FD", "BL", "WH", "WH", "BR", "FD", "WV", "WV", "FD", "BL", "WH", "WH", "TR", "TL", "WH", "WH", "BR", "FD", "WV", "WV", "FD", "BL", "WH", "WH", "BR", "FD", "WV",],
  ["WV", "FD", "FD", "FD", "FD", "FD", "FD", "WV", "WV", "FD", "FD", "FD", "FD", "WV", "WV", "FD", "FD", "FD", "FD", "WV", "WV", "FD", "FD", "FD", "FD", "FD", "FD", "WV",],
  ["BL", "WH", "WH", "WH", "WH", "TR", "FD", "WV", "BL", "WH", "WH", "TR", "FD", "WV", "WV", "FD", "TL", "WH", "WH", "BR", "WV", "FD", "TL", "WH", "WH", "WH", "WH", "BR",],
  ["ES", "ES", "ES", "ES", "ES", "WV", "FD", "WV", "TL", "WH", "WH", "BR", "FD", "BL", "BR", "FD", "BL", "WH", "WH", "TR", "WV", "FD", "WV", "ES", "ES", "ES", "ES", "ES",],
  ["ES", "ES", "ES", "ES", "ES", "WV", "FD", "WV", "WV", "FD", "FD", "FD", "FD", "ES", "ES", "FD", "FD", "FD", "FD", "WV", "WV", "FD", "WV", "ES", "ES", "ES", "ES", "ES",],
  ["ES", "ES", "ES", "ES", "ES", "WV", "FD", "WV", "WV", "FD", "TL", "WH", "WH", "GL", "GL", "WH", "WH", "TR", "FD", "WV", "WV", "FD", "WV", "ES", "ES", "ES", "ES", "ES",],
  ["ES", "WH", "WH", "WH", "WH", "BR", "FD", "BL", "BR", "FD", "WV", "BY", "ES", "ES", "ES", "ES", "PY", "WV", "FD", "BL", "BR", "FD", "BL", "WH", "WH", "WH", "WH", "ES",],
  ["0A", "FD", "FD", "FD", "FD", "FD", "PP", "FD", "FD", "FD", "WV", "ES", "ES", "ES", "ES", "ES", "ES", "WV", "FD", "FD", "FD", "PP", "FD", "FD", "FD", "FD", "FD", "0A",],
  ["ES", "WH", "WH", "WH", "WH", "TR", "FD", "TL", "TR", "FD", "WV", "ES", "IY", "ES", "ES", "CE", "ES", "WV", "FD", "TL", "TR", "FD", "TL", "WH", "WH", "WH", "WH", "ES",],
  ["ES", "ES", "ES", "ES", "ES", "WV", "FD", "WV", "WV", "FD", "BL", "WH", "WH", "WH", "WH", "WH", "WH", "BR", "FD", "WV", "WV", "FD", "WV", "ES", "ES", "ES", "ES", "ES",],
  ["ES", "ES", "ES", "ES", "ES", "WV", "FD", "WV", "WV", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "WV", "WV", "FD", "WV", "ES", "ES", "ES", "ES", "ES",],
  ["ES", "ES", "ES", "ES", "ES", "WV", "FD", "WV", "WV", "FD", "TL", "WH", "WH", "WH", "WH", "WH", "WH", "TR", "FD", "WV", "WV", "FD", "WV", "ES", "ES", "ES", "ES", "ES",],
  ["TL", "WH", "WH", "WH", "WH", "BR", "FD", "BL", "BR", "FD", "BL", "WH", "WH", "TR", "TL", "WH", "WH", "BR", "FD", "BL", "BR", "FD", "BL", "WH", "WH", "WH", "WH", "TR",],
  ["WV", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "WV", "WV", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "WV",],
  ["WV", "FD", "TL", "WH", "WH", "TR", "FD", "TL", "WH", "WH", "WH", "TR", "FD", "WV", "WV", "FD", "TL", "WH", "WH", "WH", "TR", "FD", "TL", "WH", "WH", "TR", "FD", "WV",],
  ["WV", "FD", "BL", "WH", "TR", "WV", "FD", "BL", "WH", "WH", "WH", "BR", "FD", "BL", "BR", "FD", "BL", "WH", "WH", "WH", "BR", "FD", "WV", "TL", "WH", "BR", "FD", "WV",],
  ["WV", "FD", "FD", "FD", "WV", "WV", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "PM", "ES", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "WV", "WV", "FD", "FD", "FD", "WV",],
  ["BL", "WH", "TR", "FD", "WV", "WV", "FD", "TL", "TR", "FD", "TL", "WH", "WH", "WH", "WH", "WH", "WH", "TR", "FD", "TL", "TR", "FD", "WV", "WV", "FD", "TL", "WH", "BR",],
  ["TL", "WH", "BR", "FD", "BL", "BR", "FD", "WV", "WV", "FD", "BL", "WH", "WH", "TR", "TL", "WH", "WH", "BR", "FD", "WV", "WV", "FD", "BL", "BR", "FD", "BL", "WH", "TR",],
  ["WV", "FD", "FD", "FD", "FD", "FD", "FD", "WV", "WV", "PP", "FD", "FD", "FD", "WV", "WV", "FD", "FD", "FD", "PP", "WV", "WV", "FD", "FD", "FD", "FD", "FD", "FD", "WV",],
  ["WV", "FD", "TL", "WH", "WH", "WH", "WH", "BR", "BL", "WH", "WH", "TR", "FD", "WV", "WV", "FD", "TL", "WH", "WH", "BR", "BL", "WH", "WH", "WH", "WH", "TR", "FD", "WV",],
  ["WV", "FD", "BL", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "BR", "FD", "BL", "BR", "FD", "BL", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "BR", "FD", "WV",],
  ["WV", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "WV",],
  ["BL", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "BR",],
];

export const LEVEL_2_MAP: TileType[][] = [
  ["TL", "WH", "WH", "WH", "WH", "TR", "ES", "ES", "ES", "ES", "ES", "ES", "ES", "ES", "ES", "ES", "ES", "ES", "ES", "ES", "ES", "ES", "TL", "WH", "WH", "WH", "WH", "TR"],
  ["WV", "FD", "FD", "FD", "FD", "WV", "ES", "TL", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "TR", "ES", "WV", "FD", "FD", "FD", "FD", "WV"],
  ["WV", "FD", "TL", "TR", "FD", "WV", "ES", "WV", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "WV", "ES", "WV", "FD", "TL", "TR", "FD", "WV"],
  ["WV", "FD", "WV", "WV", "FD", "WV", "ES", "WV", "FD", "TL", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "TR", "FD", "WV", "ES", "WV", "FD", "WV", "WV", "FD", "WV"],
  ["WV", "FD", "WV", "WV", "FD", "BL", "WH", "BR", "FD", "BL", "WH", "WH", "WH", "TR", "TL", "WH", "WH", "WH", "BR", "FD", "BL", "WH", "BR", "FD", "WV", "WV", "FD", "WV"],
  ["WV", "FD", "WV", "WV", "FD", "FD", "FD", "FD", "PP", "FD", "FD", "FD", "FD", "WV", "WV", "FD", "FD", "FD", "FD", "PP", "FD", "FD", "FD", "FD", "WV", "WV", "FD", "WV"],
  ["WV", "FD", "WV", "BL", "WH", "TR", "FD", "TL", "WH", "WH", "WH", "TR", "FD", "WV", "WV", "FD", "TL", "WH", "WH", "WH", "TR", "FD", "TL", "WH", "BR", "WV", "FD", "WV"],
  ["BR", "FD", "BL", "WH", "WH", "BR", "FD", "BL", "WH", "WH", "WH", "BR", "FD", "BL", "BR", "FD", "BL", "WH", "WH", "WH", "BR", "FD", "BL", "WH", "WH", "BR", "FD", "BL"],
  ["0A", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "0A"],
  ["WH", "WH", "TR", "FD", "TL", "TR", "FD", "TL", "TR", "FD", "TL", "WH", "WH", "WH", "WH", "WH", "WH", "TR", "FD", "TL", "TR", "FD", "TL", "TR", "FD", "TL", "WH", "WH"],
  ["ES", "ES", "WV", "FD", "WV", "WV", "FD", "WV", "WV", "FD", "BL", "WH", "WH", "WH", "WH", "WH", "WH", "BR", "FD", "WV", "WV", "FD", "WV", "WV", "FD", "WV", "ES", "ES"],
  ["ES", "ES", "WV", "FD", "WV", "WV", "FD", "WV", "WV", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "WV", "WV", "FD", "WV", "WV", "FD", "WV", "ES", "ES"],
  ["ES", "ES", "WV", "FD", "WV", "WV", "FD", "WV", "WV", "FD", "TL", "WH", "WH", "GL", "GL", "WH", "WH", "TR", "FD", "WV", "WV", "FD", "WV", "WV", "FD", "WV", "ES", "ES"],
  ["WH", "WH", "BR", "FD", "BL", "BR", "FD", "BL", "BR", "FD", "WV", "ES", "ES", "IY", "CE", "ES", "ES", "WV", "FD", "BL", "BR", "FD", "BL", "BR", "FD", "BL", "WH", "WH"],
  ["0B", "FD", "FD", "FD", "FD", "FD", "PP", "FD", "FD", "FD", "WV", "ES", "ES", "BY", "PY", "ES", "ES", "WV", "FD", "FD", "FD", "PP", "FD", "FD", "FD", "FD", "FD", "0B"],
  ["WH", "WH", "TR", "FD", "TL", "TR", "FD", "TL", "TR", "FD", "WV", "ES", "ES", "ES", "ES", "ES", "ES", "WV", "FD", "TL", "TR", "FD", "TL", "TR", "FD", "TL", "WH", "WH"],
  ["ES", "ES", "WV", "FD", "BL", "BR", "FD", "WV", "WV", "FD", "BL", "WH", "WH", "WH", "WH", "WH", "WH", "BR", "FD", "WV", "WV", "FD", "BL", "BR", "FD", "WV", "ES", "ES"],
  ["ES", "ES", "WV", "FD", "FD", "FD", "FD", "WV", "WV", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "WV", "WV", "FD", "FD", "FD", "FD", "WV", "ES", "ES"],
  ["ES", "ES", "BL", "WH", "WH", "TR", "FD", "WV", "WV", "FD", "TL", "WH", "WH", "WH", "WH", "WH", "WH", "TR", "FD", "WV", "WV", "FD", "TL", "WH", "WH", "BR", "ES", "ES"],
  ["TL", "WH", "WH", "WH", "WH", "BR", "FD", "BL", "BR", "FD", "BL", "WH", "WH", "WH", "WH", "WH", "WH", "BR", "FD", "BL", "BR", "FD", "BL", "WH", "WH", "WH", "WH", "TR"],
  ["WV", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "WV"],
  ["WV", "FD", "TL", "WH", "WH", "WH", "WH", "WH", "TR", "FD", "TL", "WH", "WH", "WH", "WH", "WH", "WH", "TR", "FD", "TL", "WH", "WH", "WH", "WH", "WH", "TR", "FD", "WV"],
  ["WV", "FD", "WV", "TL", "WH", "WH", "WH", "WH", "BR", "FD", "BL", "WH", "WH", "WH", "WH", "WH", "WH", "BR", "FD", "BL", "WH", "WH", "WH", "WH", "TR", "WV", "FD", "WV"],
  ["WV", "FD", "WV", "WV", "FD", "FD", "FD", "FD", "FD", "PP", "FD", "FD", "FD", "PM", "FD", "FD", "FD", "FD", "PP", "FD", "FD", "FD", "FD", "FD", "WV", "WV", "FD", "WV"],
  ["WV", "FD", "WV", "WV", "FD", "TL", "TR", "FD", "TL", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "TR", "FD", "TL", "TR", "FD", "WV", "WV", "FD", "WV"],
  ["BR", "FD", "BL", "BR", "FD", "WV", "WV", "FD", "BL", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "BR", "FD", "WV", "WV", "FD", "BL", "BR", "FD", "BL"],
  ["0C", "FD", "FD", "FD", "FD", "WV", "WV", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "WV", "WV", "FD", "FD", "FD", "FD", "0C"],
  ["TR", "FD", "TL", "WH", "WH", "BR", "BL", "WH", "WH", "WH", "WH", "TR", "FD", "TL", "TR", "FD", "TL", "WH", "WH", "WH", "WH", "BR", "BL", "WH", "WH", "TR", "FD", "TL"],
  ["WV", "FD", "BL", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "BR", "FD", "WV", "WV", "FD", "BL", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "BR", "FD", "WV"],
  ["WV", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "WV", "WV", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "WV"],
  ["BL", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "BR", "BL", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "BR"],
];

export const LEVEL_3_MAP: TileType[][] = [
  ["TL", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "TR"],
  ["WV", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "WV"],
  ["WV", "FD", "TL", "TR", "FD", "TL", "WH", "WH", "TR", "FD", "TL", "WH", "WH", "WH", "WH", "WH", "WH", "TR", "FD", "TL", "WH", "WH", "TR", "FD", "TL", "TR", "FD", "WV"],
  ["WV", "FD", "WV", "WV", "FD", "WV", "ES", "ES", "WV", "FD", "WV", "TL", "WH", "WH", "WH", "WH", "TR", "WV", "FD", "WV", "ES", "ES", "WV", "FD", "WV", "WV", "FD", "WV"],
  ["WV", "FD", "WV", "WV", "FD", "BL", "WH", "WH", "BR", "FD", "WV", "WV", "FD", "FD", "FD", "FD", "WV", "WV", "FD", "BL", "WH", "WH", "BR", "FD", "WV", "WV", "FD", "WV"],
  ["WV", "FD", "WV", "WV", "FD", "FD", "FD", "FD", "FD", "FD", "WV", "WV", "FD", "TL", "TR", "FD", "WV", "WV", "FD", "FD", "FD", "FD", "FD", "FD", "WV", "WV", "FD", "WV"],
  ["WV", "FD", "WV", "BL", "WH", "TR", "FD", "TL", "TR", "FD", "WV", "WV", "FD", "WV", "WV", "FD", "WV", "WV", "FD", "TL", "TR", "FD", "TL", "WH", "BR", "WV", "FD", "WV"],
  ["WV", "FD", "BL", "WH", "WH", "BR", "FD", "WV", "WV", "FD", "BL", "BR", "FD", "WV", "WV", "FD", "BL", "BR", "FD", "WV", "WV", "FD", "BL", "WH", "WH", "BR", "FD", "WV"],
  ["WV", "FD", "FD", "FD", "FD", "FD", "FD", "WV", "WV", "PP", "FD", "FD", "FD", "WV", "WV", "FD", "FD", "FD", "PP", "WV", "WV", "FD", "FD", "FD", "FD", "FD", "FD", "WV"],
  ["BL", "WH", "TR", "FD", "TL", "WH", "WH", "BR", "BL", "WH", "WH", "TR", "FD", "WV", "WV", "FD", "TL", "WH", "WH", "BR", "BL", "WH", "WH", "TR", "FD", "TL", "WH", "BR"],
  ["ES", "ES", "WV", "FD", "BL", "WH", "WH", "TR", "TL", "WH", "WH", "BR", "FD", "BL", "BR", "FD", "BL", "WH", "WH", "TR", "TL", "WH", "WH", "BR", "FD", "WV", "ES", "ES"],
  ["ES", "ES", "WV", "FD", "FD", "FD", "FD", "WV", "WV", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "WV", "WV", "FD", "FD", "FD", "FD", "WV", "ES", "ES"],
  ["ES", "WH", "BR", "FD", "TL", "TR", "FD", "WV", "WV", "FD", "TL", "WH", "WH", "GL", "GL", "WH", "WH", "TR", "FD", "WV", "WV", "FD", "TL", "TR", "FD", "BL", "WH", "ES"],
  ["0A", "FD", "FD", "FD", "WV", "WV", "FD", "BL", "BR", "FD", "WV", "ES", "BY", "PY", "IY", "CE", "ES", "WV", "FD", "BL", "BR", "FD", "WV", "WV", "FD", "FD", "FD", "0A"],
  ["ES", "WH", "WH", "WH", "BR", "WV", "FD", "FD", "FD", "FD", "WV", "ES", "ES", "ES", "ES", "ES", "ES", "WV", "FD", "FD", "FD", "FD", "WV", "BL", "WH", "WH", "WH", "ES"],
  ["ES", "WH", "WH", "WH", "TR", "WV", "FD", "TL", "TR", "FD", "WV", "ES", "ES", "ES", "ES", "ES", "ES", "WV", "FD", "TL", "TR", "FD", "WV", "TL", "WH", "WH", "WH", "ES"],
  ["0B", "FD", "FD", "FD", "WV", "WV", "FD", "WV", "WV", "FD", "BL", "WH", "WH", "WH", "WH", "WH", "WH", "BR", "FD", "WV", "WV", "FD", "WV", "WV", "FD", "FD", "FD", "0B"],
  ["ES", "WH", "TR", "FD", "BL", "BR", "FD", "WV", "WV", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "WV", "WV", "FD", "BL", "BR", "FD", "TL", "WH", "ES"],
  ["ES", "ES", "WV", "FD", "FD", "FD", "FD", "WV", "BL", "WH", "WH", "TR", "FD", "TL", "TR", "FD", "TL", "WH", "WH", "BR", "WV", "FD", "FD", "FD", "FD", "WV", "ES", "ES"],
  ["ES", "ES", "WV", "FD", "TL", "TR", "FD", "BL", "WH", "WH", "WH", "BR", "FD", "WV", "WV", "FD", "BL", "WH", "WH", "WH", "BR", "FD", "TL", "TR", "FD", "WV", "ES", "ES"],
  ["ES", "ES", "WV", "FD", "WV", "WV", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "WV", "WV", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "WV", "WV", "FD", "WV", "ES", "ES"],
  ["ES", "ES", "WV", "FD", "WV", "BL", "WH", "WH", "TR", "FD", "TL", "TR", "FD", "WV", "WV", "FD", "TL", "TR", "FD", "TL", "WH", "WH", "BR", "WV", "FD", "WV", "ES", "ES"],
  ["TL", "WH", "BR", "FD", "BL", "WH", "WH", "WH", "BR", "FD", "WV", "WV", "FD", "BL", "BR", "FD", "WV", "WV", "FD", "BL", "WH", "WH", "WH", "BR", "FD", "BL", "WH", "TR"],
  ["WV", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "WV", "WV", "FD", "PM", "FD", "FD", "WV", "WV", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "WV"],
  ["WV", "FD", "TL", "WH", "WH", "TR", "FD", "TL", "TR", "FD", "WV", "BL", "WH", "WH", "WH", "WH", "BR", "WV", "FD", "TL", "TR", "FD", "TL", "WH", "WH", "TR", "FD", "WV"],
  ["WV", "FD", "WV", "TL", "WH", "BR", "FD", "WV", "WV", "FD", "BL", "WH", "WH", "WH", "WH", "WH", "WH", "BR", "FD", "WV", "WV", "FD", "BL", "WH", "TR", "WV", "FD", "WV"],
  ["WV", "PP", "WV", "WV", "FD", "FD", "FD", "WV", "WV", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "WV", "WV", "FD", "FD", "FD", "WV", "WV", "PP", "WV"],
  ["WV", "FD", "WV", "WV", "FD", "TL", "WH", "BR", "BL", "WH", "WH", "TR", "FD", "TL", "TR", "FD", "TL", "WH", "WH", "BR", "BL", "WH", "TR", "FD", "WV", "WV", "FD", "WV"],
  ["WV", "FD", "BL", "BR", "FD", "BL", "WH", "WH", "WH", "WH", "WH", "BR", "FD", "WV", "WV", "FD", "BL", "WH", "WH", "WH", "WH", "WH", "BR", "FD", "BL", "BR", "FD", "WV"],
  ["WV", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "WV", "WV", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "WV"],
  ["BL", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "BR", "BL", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "BR"],
];

export const LEVEL_4_MAP: TileType[][] = [
  ["TL", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "TR"],
  ["WV", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "WV"],
  ["WV", "FD", "TL", "WH", "WH", "TR", "FD", "TL", "WH", "WH", "WH", "TR", "FD", "TL", "TR", "FD", "TL", "WH", "WH", "WH", "TR", "FD", "TL", "WH", "WH", "TR", "FD", "WV"],
  ["WV", "FD", "BL", "WH", "WH", "BR", "FD", "BL", "WH", "WH", "TR", "WV", "FD", "WV", "WV", "FD", "WV", "TL", "WH", "WH", "BR", "FD", "BL", "WH", "WH", "BR", "FD", "WV"],
  ["WV", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "PP", "WV", "WV", "FD", "WV", "WV", "FD", "WV", "WV", "PP", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "WV"],
  ["BL", "WH", "TR", "FD", "TL", "WH", "WH", "WH", "TR", "FD", "WV", "WV", "FD", "WV", "WV", "FD", "WV", "WV", "FD", "TL", "WH", "WH", "WH", "TR", "FD", "TL", "WH", "BR"],
  ["ES", "ES", "WV", "FD", "BL", "WH", "WH", "TR", "WV", "FD", "WV", "WV", "FD", "WV", "WV", "FD", "WV", "WV", "FD", "WV", "TL", "WH", "WH", "BR", "FD", "WV", "ES", "ES"],
  ["ES", "ES", "WV", "FD", "FD", "FD", "FD", "WV", "WV", "FD", "BL", "BR", "FD", "BL", "BR", "FD", "BL", "BR", "FD", "WV", "WV", "FD", "FD", "FD", "FD", "WV", "ES", "ES"],
  ["ES", "ES", "WV", "FD", "TL", "TR", "FD", "WV", "WV", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "WV", "WV", "FD", "TL", "TR", "FD", "WV", "ES", "ES"],
  ["ES", "ES", "WV", "FD", "WV", "WV", "FD", "WV", "WV", "FD", "TL", "WH", "WH", "WH", "WH", "WH", "WH", "TR", "FD", "WV", "WV", "FD", "WV", "WV", "FD", "WV", "ES", "ES"],
  ["TL", "WH", "BR", "FD", "WV", "WV", "FD", "BL", "BR", "FD", "BL", "WH", "WH", "WH", "WH", "WH", "WH", "BR", "FD", "BL", "BR", "FD", "WV", "WV", "FD", "BL", "WH", "TR"],
  ["WV", "FD", "FD", "FD", "WV", "WV", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "WV", "WV", "FD", "FD", "FD", "WV"],
  ["WV", "FD", "TL", "WH", "BR", "BL", "WH", "WH", "TR", "FD", "TL", "WH", "WH", "GL", "GL", "WH", "WH", "TR", "FD", "TL", "WH", "WH", "BR", "BL", "WH", "TR", "FD", "WV"],
  ["WV", "FD", "BL", "WH", "WH", "WH", "WH", "WH", "BR", "FD", "WV", "ES", "BY", "PY", "IY", "CE", "ES", "WV", "FD", "BL", "WH", "WH", "WH", "WH", "WH", "BR", "FD", "WV"],
  ["WV", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "WV", "ES", "ES", "ES", "ES", "ES", "ES", "WV", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "WV"],
  ["WV", "FD", "TL", "TR", "FD", "TL", "WH", "WH", "TR", "FD", "WV", "ES", "ES", "ES", "ES", "ES", "ES", "WV", "FD", "TL", "WH", "WH", "TR", "FD", "TL", "TR", "FD", "WV"],
  ["WV", "FD", "WV", "WV", "FD", "BL", "WH", "TR", "WV", "FD", "BL", "WH", "WH", "WH", "WH", "WH", "WH", "BR", "FD", "WV", "TL", "WH", "BR", "FD", "WV", "WV", "FD", "WV"],
  ["WV", "FD", "WV", "WV", "FD", "FD", "FD", "WV", "WV", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "WV", "WV", "FD", "FD", "FD", "WV", "WV", "FD", "WV"],
  ["WV", "FD", "WV", "BL", "WH", "TR", "FD", "WV", "WV", "FD", "TL", "TR", "FD", "TL", "TR", "FD", "TL", "TR", "FD", "WV", "WV", "FD", "TL", "WH", "BR", "WV", "FD", "WV"],
  ["WV", "FD", "WV", "TL", "WH", "BR", "FD", "BL", "BR", "FD", "WV", "WV", "FD", "WV", "WV", "FD", "WV", "WV", "FD", "BL", "BR", "FD", "BL", "WH", "TR", "WV", "FD", "WV"],
  ["WV", "FD", "WV", "WV", "FD", "FD", "FD", "FD", "FD", "PP", "WV", "WV", "FD", "WV", "WV", "FD", "WV", "WV", "PP", "FD", "FD", "FD", "FD", "FD", "WV", "WV", "FD", "WV"],
  ["WV", "FD", "WV", "WV", "FD", "TL", "WH", "WH", "WH", "WH", "BR", "WV", "FD", "WV", "WV", "FD", "WV", "BL", "WH", "WH", "WH", "WH", "TR", "FD", "WV", "WV", "FD", "WV"],
  ["WV", "FD", "BL", "BR", "FD", "BL", "WH", "WH", "WH", "WH", "WH", "BR", "FD", "BL", "BR", "FD", "BL", "WH", "WH", "WH", "WH", "WH", "BR", "FD", "BL", "BR", "FD", "WV"],
  ["WV", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "PM", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "WV"],
  ["WV", "FD", "TL", "TR", "FD", "TL", "WH", "WH", "TR", "FD", "TL", "WH", "WH", "WH", "WH", "WH", "WH", "TR", "FD", "TL", "WH", "WH", "TR", "FD", "TL", "TR", "FD", "WV"],
  ["WV", "FD", "WV", "WV", "FD", "BL", "WH", "TR", "WV", "FD", "BL", "WH", "WH", "TR", "TL", "WH", "WH", "BR", "FD", "WV", "TL", "WH", "BR", "FD", "WV", "WV", "FD", "WV"],
  ["WV", "FD", "WV", "WV", "FD", "FD", "FD", "WV", "WV", "FD", "FD", "FD", "FD", "WV", "WV", "FD", "FD", "FD", "FD", "WV", "WV", "FD", "FD", "FD", "WV", "WV", "FD", "WV"],
  ["WV", "FD", "WV", "BL", "WH", "TR", "FD", "WV", "WV", "FD", "TL", "TR", "FD", "WV", "WV", "FD", "TL", "TR", "FD", "WV", "WV", "FD", "TL", "WH", "BR", "WV", "FD", "WV"],
  ["WV", "FD", "BL", "WH", "WH", "BR", "FD", "BL", "BR", "FD", "WV", "WV", "FD", "BL", "BR", "FD", "WV", "WV", "FD", "BL", "BR", "FD", "BL", "WH", "WH", "BR", "FD", "WV"],
  ["WV", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "WV", "WV", "FD", "FD", "FD", "FD", "WV", "WV", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "WV"],
  ["BL", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "BR", "BL", "WH", "WH", "WH", "WH", "BR", "BL", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "BR"],
];

export const LEVEL_5_MAP: TileType[][] = [
  ["TL", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "TR", "TL", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "TR"],
  ["WV", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "WV", "WV", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "WV"],
  ["WV", "FD", "TL", "WH", "WH", "TR", "FD", "TL", "WH", "WH", "WH", "TR", "FD", "WV", "WV", "FD", "TL", "WH", "WH", "WH", "TR", "FD", "TL", "WH", "WH", "TR", "FD", "WV"],
  ["WV", "FD", "BL", "WH", "WH", "BR", "FD", "BL", "WH", "WH", "TR", "WV", "FD", "WV", "WV", "FD", "WV", "TL", "WH", "WH", "BR", "FD", "BL", "WH", "WH", "BR", "FD", "WV"],
  ["WV", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "WV", "WV", "FD", "BL", "BR", "FD", "WV", "WV", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "WV"],
  ["BL", "WH", "WH", "TR", "FD", "TL", "WH", "WH", "TR", "FD", "WV", "WV", "FD", "FD", "FD", "FD", "WV", "WV", "FD", "TL", "WH", "WH", "TR", "FD", "TL", "WH", "WH", "BR"],
  ["TL", "WH", "WH", "BR", "FD", "BL", "WH", "TR", "WV", "FD", "WV", "WV", "FD", "TL", "TR", "FD", "WV", "WV", "FD", "WV", "TL", "WH", "BR", "FD", "BL", "WH", "WH", "TR"],
  ["WV", "FD", "FD", "FD", "FD", "FD", "PP", "WV", "WV", "FD", "BL", "BR", "FD", "WV", "WV", "FD", "BL", "BR", "FD", "WV", "WV", "PP", "FD", "FD", "FD", "FD", "FD", "WV"],
  ["WV", "FD", "TL", "WH", "WH", "TR", "FD", "WV", "WV", "FD", "FD", "FD", "FD", "WV", "WV", "FD", "FD", "FD", "FD", "WV", "WV", "FD", "TL", "WH", "WH", "TR", "FD", "WV"],
  ["WV", "FD", "BL", "WH", "TR", "WV", "FD", "WV", "WV", "FD", "TL", "WH", "WH", "BR", "BL", "WH", "WH", "TR", "FD", "WV", "WV", "FD", "WV", "TL", "WH", "BR", "FD", "WV"],
  ["WV", "FD", "FD", "FD", "WV", "WV", "FD", "BL", "BR", "FD", "BL", "WH", "WH", "WH", "WH", "WH", "WH", "BR", "FD", "BL", "BR", "FD", "WV", "WV", "FD", "FD", "FD", "WV"],
  ["WV", "FD", "FD", "FD", "WV", "WV", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "WV", "WV", "FD", "FD", "FD", "WV"],
  ["BL", "WH", "TR", "FD", "WV", "WV", "FD", "TL", "TR", "FD", "TL", "WH", "WH", "GL", "GL", "WH", "WH", "TR", "FD", "TL", "TR", "FD", "WV", "WV", "FD", "TL", "WH", "BR"],
  ["ES", "WH", "BR", "FD", "BL", "BR", "FD", "WV", "WV", "FD", "WV", "ES", "ES", "ES", "ES", "ES", "ES", "WV", "FD", "WV", "WV", "FD", "BL", "BR", "FD", "BL", "WH", "ES"],
  ["0A", "FD", "FD", "FD", "FD", "FD", "FD", "WV", "WV", "FD", "WV", "ES", "BY", "PY", "IY", "CE", "ES", "WV", "FD", "WV", "WV", "FD", "FD", "FD", "FD", "FD", "FD", "0A"],
  ["ES", "WH", "TR", "FD", "TL", "WH", "WH", "BR", "WV", "FD", "WV", "ES", "ES", "ES", "ES", "ES", "ES", "WV", "FD", "WV", "BL", "WH", "WH", "TR", "FD", "TL", "WH", "ES"],
  ["TL", "WH", "BR", "FD", "BL", "WH", "WH", "WH", "BR", "FD", "BL", "WH", "WH", "WH", "WH", "WH", "WH", "BR", "FD", "BL", "WH", "WH", "WH", "BR", "FD", "BL", "WH", "TR"],
  ["WV", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "PP", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "PP", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "WV"],
  ["WV", "FD", "TL", "WH", "WH", "TR", "FD", "TL", "TR", "FD", "TL", "WH", "WH", "WH", "WH", "WH", "WH", "TR", "FD", "TL", "TR", "FD", "TL", "WH", "WH", "TR", "FD", "WV"],
  ["WV", "FD", "WV", "TL", "WH", "BR", "FD", "WV", "WV", "FD", "BL", "WH", "WH", "TR", "TL", "WH", "WH", "BR", "FD", "WV", "WV", "FD", "BL", "WH", "TR", "WV", "FD", "WV"],
  ["WV", "FD", "WV", "WV", "FD", "FD", "FD", "WV", "WV", "FD", "FD", "FD", "FD", "WV", "WV", "FD", "FD", "FD", "FD", "WV", "WV", "FD", "FD", "FD", "WV", "WV", "FD", "WV"],
  ["WV", "FD", "WV", "WV", "FD", "TL", "WH", "BR", "BL", "WH", "WH", "TR", "FD", "WV", "WV", "FD", "TL", "WH", "WH", "BR", "BL", "WH", "TR", "FD", "WV", "WV", "FD", "WV"],
  ["WV", "FD", "BL", "BR", "FD", "BL", "WH", "WH", "WH", "WH", "WH", "BR", "FD", "BL", "BR", "FD", "BL", "WH", "WH", "WH", "WH", "WH", "BR", "FD", "BL", "BR", "FD", "WV"],
  ["WV", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "PM", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "WV"],
  ["BL", "WH", "WH", "WH", "WH", "WH", "TR", "FD", "TL", "TR", "FD", "TL", "WH", "WH", "WH", "WH", "TR", "FD", "TL", "TR", "FD", "TL", "WH", "WH", "WH", "WH", "WH", "BR"],
  ["TL", "WH", "WH", "WH", "WH", "WH", "BR", "FD", "WV", "WV", "FD", "BL", "WH", "TR", "TL", "WH", "BR", "FD", "WV", "WV", "FD", "BL", "WH", "WH", "WH", "WH", "WH", "TR"],
  ["WV", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "WV", "WV", "FD", "FD", "FD", "WV", "WV", "FD", "FD", "FD", "WV", "WV", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "WV"],
  ["WV", "FD", "TL", "WH", "WH", "WH", "WH", "WH", "BR", "BL", "WH", "TR", "FD", "WV", "WV", "FD", "TL", "WH", "BR", "BL", "WH", "WH", "WH", "WH", "WH", "TR", "FD", "WV"],
  ["WV", "FD", "BL", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "BR", "FD", "WV", "WV", "FD", "BL", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "BR", "FD", "WV"],
  ["WV", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "WV", "WV", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "FD", "WV"],
  ["BL", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "BR", "BL", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "WH", "BR"],
];

